### ISSUE TITLE
Homey Bridge

### ISSUE THREAD

**Issue by Lexan76** [ThomasHoussin/com.thomashoussin.fronius#21]
Any news about support for homey bridge?

**Comment by ThomasHoussin** [comment]
OK I had a look. 
- that's not the API I use
- this is not a public API : "In order to access and use the API customers need to be registered in Solar.web (https://www.solarweb.com) and sign a contract with Fronius to get access to SWQAPI.". I do not have access, but I'll ask for it and see. 
- developers have to pay to be able to publish cloud-apps ; even if I add this API, I will not publish it to homey cloud.
